#!/bin/bash

HERE=$(dirname $(realpath $0))

inv=${1}
shift

IMAGE=kubespray-$LOGNAME
docker build -t $IMAGE . || exit 1

set -x
exec docker run -ti --rm -v /localdisk:/localdisk -w $HERE $IMAGE  ansible-playbook -i inventory/${inv}/hosts.yml -b "$@"

