#!/bin/bash

build=false
if [ "$1" == "--build" ]; then
    shift
    build=true
fi

#IMAGE="artifactory.riftio.com/docker/k8sclient"
HERE=$(dirname $(realpath $0))

inv=${1}
shift

set -x
#docker pull $IMAGE
IMAGE=jlm1

if $build; then
    docker build -t $IMAGE .
fi

exec docker run -ti --rm -v /localdisk:/localdisk -w $HERE $IMAGE  ansible-playbook -i inventory/${inv}/hosts.yml -b "$@"

